export const defaultConfig = {
  debug: new URLSearchParams(window.location.search).has("debug"),
  enxCloak: true,
  enxConvert: true,
  enxDonate: true,
  enxEmailTarget: true,
  enxHtml: true,
  enxModel: true,
  enxMultiStepForm: true,
  enxProxyFields: true,
  enxReadMoreMobile: true,
  enxShare: true,
  enxShow: true,
  enxText: true,
  enxTweetTarget: true,
  enxValidate: {
    removeErrorsOnInput: true,
    sortCodeField: "supporter.bankRoutingNumber",
    accountNumberField: "supporter.bankAccountNumber",
  },
  beforeInit: () => {},
  beforeCloakRemoval: () => {},
  afterInit: () => {},
};
